
export const LAUNCH_DATA_FETCHED = 'LAUNCH_DATA_FETCHED';
export const ROCKET_DATA_FETCHED = 'ROCKET_DATA_FETCHED';
export const MISSION_DATA_FETCHED = 'MISSION_DATA_FETCHED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';